-- 078: Tokenized W-9 submission (no account required)
--
-- Musicians used to upload a W-9 from the portal profile page. That required a
-- login, so it only ever worked for the minority who created an account —
-- everyone else emailed a PDF to the contractor, who re-uploaded it by hand. The
-- portal is gone, so this replaces it with the same pattern the rest of the
-- musician experience already uses: a tokenized link in an email.
--
-- The result is strictly more capable than what it replaces: every musician can
-- now submit their own W-9, not just account holders.
--
-- Storage, status and the admin download are unchanged — the upload sets the
-- same musicians.w9_on_file / w9_file_url columns the dashboard already reads,
-- so the existing badges, the has_w9 / no_w9 filter, the download link and
-- verification flow light up with no UI changes.

-- 1. Request token. 256 bits from gen_random_bytes, matching contract_offers.
--    NOT generated by default: a token only exists once a request is actually
--    sent, so a musician who was never asked has no live upload link.
ALTER TABLE musicians
  ADD COLUMN IF NOT EXISTS w9_request_token      TEXT,
  ADD COLUMN IF NOT EXISTS w9_request_sent_at    TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS w9_request_expires_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS w9_uploaded_at        TIMESTAMPTZ;

-- One musician per token. Also gives the /w9/[token] lookup an index.
CREATE UNIQUE INDEX IF NOT EXISTS idx_musicians_w9_request_token
  ON musicians(w9_request_token)
  WHERE w9_request_token IS NOT NULL;

COMMENT ON COLUMN musicians.w9_request_token IS
  'Single-musician upload token for /w9/[token]. Set when a W-9 request email is '
  'sent, cleared on successful upload. NULL means no live upload link.';
COMMENT ON COLUMN musicians.w9_uploaded_at IS
  'When the musician submitted their own W-9 through the tokenized link. NULL for '
  'W-9s the contractor uploaded on their behalf, so the two are distinguishable.';

-- 2. Remove the storage policies that keyed on auth.uid().
--
--    Migration 032 gave musicians insert/select/update/delete on their own folder
--    in w9-documents, scoped by `(storage.foldername(name))[1] = auth.uid()`.
--    Musicians no longer have accounts, so auth.uid() is never a musician and
--    these four policies can never match — they are dead weight that reads like
--    a live grant. The upload route uses the service role, which bypasses RLS.
--
--    "Admin read all W9" (service_role) is deliberately kept: the admin download
--    route at /api/musicians/[id]/w9 relies on it.
DROP POLICY IF EXISTS "Musicians upload own W9" ON storage.objects;
DROP POLICY IF EXISTS "Musicians read own W9"   ON storage.objects;
DROP POLICY IF EXISTS "Musicians update own W9" ON storage.objects;
DROP POLICY IF EXISTS "Musicians delete own W9" ON storage.objects;

-- verify: the new columns exist. Expect 4 rows.
-- SELECT column_name, data_type FROM information_schema.columns
-- WHERE table_name = 'musicians' AND column_name LIKE 'w9_%request%' OR column_name = 'w9_uploaded_at';

-- verify: no musician-facing storage policy survives on the W-9 bucket.
-- Expect only "Admin read all W9".
-- SELECT policyname, cmd FROM pg_policies
-- WHERE schemaname = 'storage' AND tablename = 'objects'
--   AND policyname ILIKE '%W9%';

-- verify: no live upload tokens yet (nothing sent since the migration). Expect 0.
-- SELECT count(*) FROM musicians WHERE w9_request_token IS NOT NULL;
